require_relative '../node_modules/react-native-test-app/macos/test_app.rb'

workspace 'Example.xcworkspace'

use_test_app! do |target|
  target.tests do
    pod 'Example-Tests', :path => '..'
  end
end

# target 'ReactTestApp' do
#   # Your react-native and other pods

#   pod 'RNSentry', :podspec => '../node_modules/@sentry/react-native/RNSentry.podspec' # or your path to node_modules
# end
